// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.DAL.ContextClasses;

#nullable disable

namespace Project.DAL.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240529154501_dd")]
    partial class dd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 617, DateTimeKind.Local).AddTicks(4742),
                            Name = "Admin",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 617, DateTimeKind.Local).AddTicks(4802),
                            Name = "Member",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 617, DateTimeKind.Local).AddTicks(4814),
                            Name = "Developer",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("ActivationCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Agree")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Sports",
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 617, DateTimeKind.Local).AddTicks(4829),
                            Description = "Koştum sıradanlıktan camisi teldeki sevindi.\nGidecekmiş sit sıradanlıktan suscipit gördüm aspernatur.\nCezbelendi koyun sit dolorem gülüyorum explicabo bilgisayarı qui numquam modi.\nQuis accusantium telefonu eum consequatur.\nÇünkü şafak voluptatem quis aut sarmal salladı.\nEt lambadaki nostrum et bahar quaerat.\nLaboriosam laudantium dağılımı voluptatem qui ut ut.\nİusto in quis nisi blanditiis un quasi ışık neque.\nŞafak düşünüyor ipsum consequuntur molestiae aut iure ipsum yaptı aut.\nQuia gülüyorum labore nisi otobüs totam camisi batarya tv.",
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Beauty",
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 617, DateTimeKind.Local).AddTicks(6265),
                            Description = "Teldeki quis gülüyorum autem un kutusu aut.\nQui gördüm orta ama consequuntur.\nMasaya sıfat adresini aperiam aut et praesentium nisi.\nNostrum neque enim doğru sıfat sed ama.\nİnventore kalemi yapacakmış nemo gazete.\nLabore magnam olduğu enim.\nİpsa lakin modi beğendim aut tv et.\nVoluptate ışık numquam quia enim ipsam ipsa ekşili.\nDignissimos nemo dignissimos enim nihil bilgiyasayarı dağılımı autem mıknatıslı.\nDeleniti in voluptatem ipsa et tv labore.",
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Games",
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 617, DateTimeKind.Local).AddTicks(6597),
                            Description = "Eaque rem labore beatae yaptı sit ut anlamsız.\nAccusantium gazete doloremque adanaya in voluptas sıradanlıktan.\nQuasi nesciunt fugit anlamsız et dignissimos mıknatıslı çorba sinema quam.\nDe patlıcan ducimus ea laudantium.\nMagni bilgiyasayarı voluptatem göze sequi sarmal voluptatum adipisci.\nKoyun ut ipsum filmini modi dergi.\nSunt suscipit mutlu praesentium alias amet dignissimos in ex.\nEt masaya quam.\nMasanın dicta un quia bilgisayarı de.\nVelit teldeki lambadaki iusto magnam domates bundan hesap.",
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Industrial",
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 617, DateTimeKind.Local).AddTicks(6844),
                            Description = "Layıkıyla magni de iure sandalye veniam voluptas sed lambadaki.\nSed yapacakmış veritatis batarya.\nAçılmadan bahar quaerat lambadaki velit sit bilgisayarı koyun ratione düşünüyor.\nUt mi qui odio.\nAutem sıfat architecto laudantium domates suscipit bundan quia karşıdakine.\nAlias in ve salladı mıknatıslı qui.\nLayıkıyla quia aspernatur orta koştum vitae mıknatıslı quis ötekinden sıla.\nSarmal dışarı ötekinden düşünüyor quasi cezbelendi mi.\nDışarı vel sokaklarda veniam dağılımı voluptatem consequatur doloremque.\nOdit çorba ötekinden et layıkıyla et çünkü sunt incidunt.",
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Health",
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 617, DateTimeKind.Local).AddTicks(7641),
                            Description = "Gördüm okuma ipsum fugit sit odio.\nVoluptate yaptı commodi.\nKoyun kutusu eos magni ötekinden.\nTv domates çobanın ea de gül.\nHesap dolores beğendim yapacakmış duyulmamış camisi.\nQuia beatae accusantium ekşili eos aut.\nQui incidunt ve reprehenderit dolore mi quia ad cesurca.\nOdit sıla dışarı voluptate tempora duyulmamış enim gazete neque layıkıyla.\nUzattı filmini voluptas suscipit un aspernatur de dolore göze eum.\nKi dışarı un ut balıkhaneye gülüyorum.",
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            CategoryName = "Home",
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 617, DateTimeKind.Local).AddTicks(7914),
                            Description = "Un sıla orta.\nİpsum filmini doloremque yaptı sit ea ve quis sıradanlıktan tv.\nPerferendis adanaya değirmeni.\nAb salladı quia inventore minima quia ratione aut cezbelendi qui.\nEum gitti dolorem.\nDolore qui aut aut yazın architecto.\nİn veniam kutusu yaptı yapacakmış nesciunt ekşili.\nBiber neque orta cezbelendi yapacakmış kalemi qui.\nMakinesi ona makinesi ama iusto beğendim gülüyorum koyun aut.\nVeritatis yazın qui enim esse.",
                            Status = 1
                        },
                        new
                        {
                            ID = 7,
                            CategoryName = "Outdoors",
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 617, DateTimeKind.Local).AddTicks(8100),
                            Description = "Neque masaya ut minima amet voluptate illo quia çarpan karşıdakine.\nDoğru qui doloremque quis consequatur bilgiyasayarı sayfası değirmeni ipsam.\nDağılımı modi eum corporis yapacakmış tv ışık masanın.\nÇobanın et camisi sit.\nSıla gördüm quia.\nGülüyorum neque koştum.\nNostrum quis oldular gül.\nAliquid corporis consectetur aliquid salladı numquam voluptate.\nBlanditiis balıkhaneye sıla eius duyulmamış kutusu.\nAut tv domates quam magnam anlamsız çobanın totam değerli.",
                            Status = 1
                        },
                        new
                        {
                            ID = 8,
                            CategoryName = "Home",
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 617, DateTimeKind.Local).AddTicks(8278),
                            Description = "Ötekinden salladı ona aperiam ea.\nSuscipit laboriosam illo adanaya enim ea.\nAdresini karşıdakine eum.\nAma ullam laboriosam ama sed.\nGidecekmiş anlamsız voluptate quia labore deleniti.\nAccusantium voluptatem mutlu veniam.\nReprehenderit accusantium doğru lambadaki quasi cesurca aspernatur.\nMasanın nisi ut değirmeni dolayı tempora veritatis öyle.\nSandalye iure dicta sayfası aliquam voluptate quae dicta sarmal.\nDoloremque voluptatem velit quia sed gazete aliquam gül illo quia.",
                            Status = 1
                        },
                        new
                        {
                            ID = 9,
                            CategoryName = "Beauty",
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 617, DateTimeKind.Local).AddTicks(8453),
                            Description = "Quia telefonu gitti nihil öyle corporis labore.\nMıknatıslı quia dignissimos ona qui kutusu.\nAb magni velit ea mi quia.\nConsectetur ki eaque ve orta iusto in eos.\nKoştum deleniti ut praesentium ışık quia inventore layıkıyla bilgisayarı beatae.\nCorporis de et şafak quaerat qui.\nEnim consectetur bilgiyasayarı.\nOna adresini consequuntur suscipit quia voluptatem laboriosam.\nEt exercitationem çıktılar lakin suscipit enim doğru düşünüyor.\nOlduğu perferendis ut bundan eum kutusu eum praesentium ötekinden.",
                            Status = 1
                        },
                        new
                        {
                            ID = 10,
                            CategoryName = "Kids",
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 617, DateTimeKind.Local).AddTicks(8666),
                            Description = "Explicabo beğendim praesentium veniam karşıdakine incidunt.\nYaptı mi sıla.\nKarşıdakine reprehenderit eos laboriosam eos fugit teldeki koşuyorlar.\nCamisi ut molestiae voluptate eius ut.\nAçılmadan sandalye cesurca balıkhaneye ışık dolore et.\nGöze deleniti minima biber beatae ab voluptate koştum.\nSayfası ad ea doloremque doğru uzattı.\nSıradanlıktan voluptatum sıfat minima doğru.\nMagni dergi ipsam.\nLaboriosam göze tv beatae sit cezbelendi düşünüyor.",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AppUserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnitInStock")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 617, DateTimeKind.Local).AddTicks(9499),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Licensed Concrete Keyboard",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 552.85m
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 2,
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 617, DateTimeKind.Local).AddTicks(9784),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Handcrafted Metal Keyboard",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 232.59m
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 3,
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 617, DateTimeKind.Local).AddTicks(9891),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Awesome Granite Hat",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 992.80m
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 4,
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 617, DateTimeKind.Local).AddTicks(9936),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Tasty Plastic Bacon",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 260.34m
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 5,
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 617, DateTimeKind.Local).AddTicks(9976),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Generic Fresh Cheese",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 176.54m
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 6,
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 618, DateTimeKind.Local).AddTicks(14),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Awesome Cotton Car",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 183.84m
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 7,
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 618, DateTimeKind.Local).AddTicks(92),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Licensed Granite Mouse",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 875.76m
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 8,
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 618, DateTimeKind.Local).AddTicks(130),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Gorgeous Wooden Sausages",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 537.64m
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 9,
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 618, DateTimeKind.Local).AddTicks(167),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Incredible Steel Bacon",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 911.31m
                        },
                        new
                        {
                            ID = 10,
                            CategoryID = 10,
                            CreatedDate = new DateTime(2024, 5, 29, 18, 45, 0, 618, DateTimeKind.Local).AddTicks(206),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Handcrafted Steel Tuna",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 505.18m
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.UserProfile", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserRole", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithMany("Orders")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.OrderDetail", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.UserProfile", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithOne("UserProfile")
                        .HasForeignKey("Project.ENTITIES.Models.UserProfile", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("UserProfile")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
