// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.DAL.ContextClasses;

#nullable disable

namespace Project.DAL.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240519174836_Index")]
    partial class Index
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 540, DateTimeKind.Local).AddTicks(9889),
                            Name = "Admin",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 540, DateTimeKind.Local).AddTicks(9963),
                            Name = "Member",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Books",
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(31),
                            Description = "Dolor sayfası voluptatum eius salladı eius nisi.\nEkşili nostrum mi ipsum corporis.\nOrta ab quia aut ipsa explicabo.\nNihil ut voluptatem.\nÖyle tv aliquam masaya exercitationem.\nÇünkü beatae çıktılar minima.\nSit quaerat non.\nTeldeki domates umut mutlu iure minima.\nKarşıdakine inventore voluptatem quis.\nVe sandalye quia commodi.",
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Music",
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(647),
                            Description = "Sayfası voluptatum nostrum ışık vitae kulu ducimus ipsam architecto anlamsız.\nSinema adanaya vitae consequatur iure vel quasi illo alias türemiş.\nQuia masaya voluptatum fugit adresini balıkhaneye perferendis ut doğru sıla.\nBilgisayarı tempora lambadaki ut sıla ki çünkü ki quia.\nAd reprehenderit consectetur bilgisayarı dignissimos deleniti.\nDolayı dağılımı kalemi makinesi ex sit şafak düşünüyor.\nAliquid qui batarya reprehenderit eius lambadaki.\nNeque ex domates blanditiis.\nUt masaya ad.\nQuis esse praesentium.",
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Health",
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(906),
                            Description = "Sıradanlıktan quis iure voluptatem sevindi.\nVoluptatum adanaya ab değerli sed qui doloremque.\nCamisi suscipit biber çünkü filmini.\nAut sequi değerli nostrum.\nVeritatis nemo sarmal dolorem ratione bundan gül quae ullam gördüm.\nSalladı velit minima koyun veniam.\nDüşünüyor minima adipisci anlamsız illo.\nSuscipit qui veniam ullam camisi.\nEa inventore adresini mi sıfat.\nQui mıknatıslı in.",
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Toys",
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(1101),
                            Description = "Dışarı için perferendis.\nGitti nostrum dicta laboriosam adipisci.\nTempora ona sıla sit çakıl mıknatıslı.\nQuam deleniti qui orta otobüs ut ona sıla voluptatem.\nBalıkhaneye voluptate amet et iure blanditiis dicta yazın.\nQui camisi alias perferendis magnam.\nYaptı gül sinema sandalye tempora uzattı çakıl için.\nYaptı un kalemi molestiae.\nBlanditiis camisi deleniti qui dışarı totam sandalye sed.\nKoşuyorlar ötekinden gazete adipisci ki quasi sıla.",
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Movies",
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(1306),
                            Description = "Ut quasi quia sequi.\nMagni aut düşünüyor dağılımı dergi vel.\nVoluptate et dolayı otobüs kapının accusantium.\nİpsa gördüm dolor quasi aperiam totam.\nBilgisayarı laboriosam kulu eaque.\nAut reprehenderit kutusu filmini consectetur batarya architecto.\nQuia mutlu architecto.\nSed dignissimos layıkıyla dicta qui masaya numquam sokaklarda.\nŞafak cesurca sıfat vitae gidecekmiş.\nLaboriosam batarya neque molestiae sokaklarda gidecekmiş bahar exercitationem vitae değirmeni.",
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            CategoryName = "Automotive",
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(1503),
                            Description = "Nostrum labore magni domates quae quis.\nUn iure ut quis.\nOna batarya ipsum lambadaki ve.\nBeğendim architecto minima ad ut eum illo.\nEnim dolore nemo.\nDolayı inventore ama otobüs nostrum esse veritatis düşünüyor gitti.\nSuscipit bilgisayarı et gazete duyulmamış consequatur bilgisayarı.\nPerferendis masaya quasi nostrum blanditiis göze gazete laboriosam exercitationem.\nDignissimos ipsam quis ona commodi voluptate fugit ve consequatur corporis.\nÇorba gül consectetur reprehenderit bilgiyasayarı eius sinema oldular dolor.",
                            Status = 1
                        },
                        new
                        {
                            ID = 7,
                            CategoryName = "Movies",
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(1700),
                            Description = "Enim dergi sokaklarda.\nAdresini dışarı sayfası ad enim layıkıyla vitae voluptas bilgisayarı perferendis.\nÇakıl mıknatıslı aut nostrum sıla nostrum çakıl dicta suscipit tempora.\nAdipisci incidunt sit kalemi iure ab patlıcan eius.\nGazete sunt çünkü umut odit voluptatem bahar non masanın.\nTelefonu uzattı ex praesentium.\nAdipisci sıfat reprehenderit ekşili için sequi minima teldeki laudantium.\nVelit koştum corporis sinema salladı.\nSed aliquid cezbelendi çarpan camisi masaya.\nKulu düşünüyor çıktılar çıktılar explicabo fugit çorba sed.",
                            Status = 1
                        },
                        new
                        {
                            ID = 8,
                            CategoryName = "Grocery",
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(1894),
                            Description = "Alias suscipit beatae.\nUmut consequatur tv rem quia ex anlamsız sunt ad.\nKoştum praesentium ut voluptatem dolor masaya açılmadan nemo voluptatem.\nPatlıcan olduğu un dolayı sit.\nEnim umut beğendim çarpan velit koştum.\nHesap deleniti domates ipsa kulu velit.\nEt reprehenderit teldeki yapacakmış oldular çünkü.\nConsequatur mıknatıslı kapının okuma quia camisi et alias adipisci.\nOlduğu quia teldeki.\nLabore de sokaklarda adanaya exercitationem.",
                            Status = 1
                        },
                        new
                        {
                            ID = 9,
                            CategoryName = "Health",
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(2092),
                            Description = "Sit sunt adipisci accusantium tv quia quia oldular ab.\nOldular ab dignissimos.\nQuia dolore layıkıyla.\nDignissimos nesciunt dolor nostrum.\nMıknatıslı autem ducimus et ullam bundan bundan aliquam amet.\nDergi salladı qui voluptatum ötekinden beatae.\nGördüm göze cesurca explicabo ötekinden qui sıla mi duyulmamış.\nEaque praesentium anlamsız uzattı yazın enim yapacakmış.\nBahar laboriosam iusto gitti kapının olduğu.\nMinima commodi adresini.",
                            Status = 1
                        },
                        new
                        {
                            ID = 10,
                            CategoryName = "Books",
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(2358),
                            Description = "Dolor alias gülüyorum kapının eius adipisci koştum non.\nConsequatur ut kutusu vel ex vel ea un ipsum architecto.\nModi praesentium telefonu consequatur adanaya blanditiis modi dolore.\nGördüm commodi quis.\nSıradanlıktan ötekinden perferendis tv çünkü ut sokaklarda uzattı gülüyorum.\nVel quia aliquam consequuntur değerli.\nDışarı aliquid architecto otobüs.\nÇobanın beğendim çünkü hesap lambadaki umut sit teldeki iure iusto.\nUn quae kulu ki patlıcan beatae düşünüyor.\nVoluptatem ut otobüs gülüyorum ullam explicabo sıfat değerli.",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AppUserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnitInStock")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(2686),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Tasty Rubber Pizza",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 356.89m
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 2,
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(2952),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Intelligent Soft Bike",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 494.77m
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 3,
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(3045),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Incredible Plastic Pizza",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 509.05m
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 4,
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(3090),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Awesome Cotton Tuna",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 686.28m
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 5,
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(3132),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Sleek Soft Cheese",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 233.81m
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 6,
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(3172),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Rustic Frozen Bike",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 328.28m
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 7,
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(3230),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Intelligent Cotton Towels",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 9.68m
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 8,
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(3269),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Refined Fresh Keyboard",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 680.33m
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 9,
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(3310),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Rustic Frozen Table",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 877.90m
                        },
                        new
                        {
                            ID = 10,
                            CategoryID = 10,
                            CreatedDate = new DateTime(2024, 5, 19, 20, 48, 36, 541, DateTimeKind.Local).AddTicks(3349),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Incredible Frozen Bike",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 384.34m
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.UserProfile", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserRole", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithMany("Orders")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.OrderDetail", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.UserProfile", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithOne("UserProfile")
                        .HasForeignKey("Project.ENTITIES.Models.UserProfile", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("UserProfile")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
