// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.DAL.ContextClasses;

#nullable disable

namespace Project.DAL.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240521114321_dd")]
    partial class dd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 427, DateTimeKind.Local).AddTicks(7696),
                            Name = "Admin",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 427, DateTimeKind.Local).AddTicks(7764),
                            Name = "Member",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("ActivationCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Tools",
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 427, DateTimeKind.Local).AddTicks(7784),
                            Description = "Quis quam minima quia dolor aliquam quia nesciunt nemo okuma.\nDe numquam quia çarpan sokaklarda mıknatıslı laudantium.\nBeatae gülüyorum aut anlamsız.\nMutlu mutlu mi orta.\nSevindi bilgiyasayarı telefonu uzattı.\nSıfat tempora ve ötekinden ad çobanın bundan sokaklarda.\nKoştum çarpan inventore aspernatur ki dolore aliquid nisi camisi doğru.\nSed ut domates aut.\nCommodi fugit koşuyorlar aut nostrum commodi ullam velit sevindi mi.\nMakinesi enim sayfası layıkıyla molestiae layıkıyla eaque karşıdakine nostrum.",
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Health",
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 427, DateTimeKind.Local).AddTicks(8287),
                            Description = "Sinema için ducimus.\nEnim laudantium okuma sandalye ki batarya ratione quae dolores eos.\nEsse ipsam ut dolayı aliquid labore sed quaerat.\nMinima quae deleniti aperiam rem.\nGül odio perferendis nostrum sit.\nEa makinesi makinesi okuma bilgiyasayarı quia.\nMasaya rem adanaya dışarı ratione ipsam.\nAd değerli ama illo quasi sed.\nDüşünüyor illo ama vel teldeki gördüm gazete.\nOlduğu adipisci doğru koyun koyun biber tempora qui koştum voluptas.",
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Movies",
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 427, DateTimeKind.Local).AddTicks(8502),
                            Description = "Dolorem quis magni.\nDucimus aut okuma biber quia qui ea karşıdakine.\nDeğerli veniam commodi için için.\nQuia yapacakmış ışık veniam adipisci telefonu praesentium karşıdakine beğendim.\nBiber blanditiis layıkıyla dolore et cezbelendi.\nCorporis dergi dolor layıkıyla dicta yazın karşıdakine.\nBilgiyasayarı beatae autem bilgisayarı commodi biber lambadaki.\nEsse fugit consequatur totam vel perferendis illo veritatis dağılımı.\nDicta dolor aspernatur otobüs voluptatum ona quia.\nDağılımı un bilgisayarı dolor.",
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Shoes",
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 427, DateTimeKind.Local).AddTicks(8716),
                            Description = "Exercitationem aut dergi orta okuma.\nEkşili nihil mıknatıslı quasi ötekinden otobüs et consequatur filmini.\nBilgisayarı quia değerli molestiae nemo qui perferendis.\nSokaklarda çarpan sandalye ki suscipit sequi teldeki otobüs cesurca.\nEt deleniti lakin değerli ut aperiam oldular exercitationem sıradanlıktan.\nUllam açılmadan umut ama inventore velit fugit.\nYapacakmış quis sit dışarı öyle in ea ipsam ipsum vitae.\nEve ut veniam umut ratione incidunt sayfası accusantium gül.\nVeniam neque değerli sarmal için.\nGöze mi non blanditiis cesurca quaerat.",
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Music",
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 427, DateTimeKind.Local).AddTicks(8921),
                            Description = "Consectetur makinesi mıknatıslı.\nOrta velit dignissimos orta makinesi eius açılmadan aliquid.\nDignissimos suscipit ex.\nDüşünüyor değerli oldular quam.\nOna layıkıyla corporis qui quia koştum mutlu anlamsız.\nSit ki bilgisayarı.\nAmet modi suscipit açılmadan.\nMolestiae sit yazın sevindi anlamsız öyle minima hesap koşuyorlar.\nCommodi eve adipisci değerli numquam aspernatur qui consequatur.\nAd magni ki iure exercitationem ut gidecekmiş yaptı.",
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            CategoryName = "Games",
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 427, DateTimeKind.Local).AddTicks(9084),
                            Description = "Ut ipsam sıfat sed sequi gül koştum.\nVelit mutlu sinema nesciunt quia yapacakmış dağılımı koştum in.\nAma sunt ullam dolorem.\nAmet tempora consequatur aut commodi iusto bundan nostrum olduğu sıfat.\nAnlamsız explicabo sit numquam sayfası kalemi voluptatem.\nMıknatıslı çorba nisi aut sinema gazete.\nİpsa velit yaptı ipsum.\nAdipisci ve qui et explicabo consequatur.\nDeğirmeni enim dolores duyulmamış minima göze aut dolorem neque.\nİnventore yazın öyle nihil tv adipisci.",
                            Status = 1
                        },
                        new
                        {
                            ID = 7,
                            CategoryName = "Movies",
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 427, DateTimeKind.Local).AddTicks(9292),
                            Description = "Qui dergi voluptatem qui teldeki dicta aut vel bilgiyasayarı çakıl.\nMakinesi inventore quia illo gülüyorum minima batarya beğendim eaque aliquid.\nGöze cezbelendi quasi commodi quis veniam türemiş.\nNostrum batarya quae balıkhaneye.\nDomates masanın batarya dolor sıradanlıktan.\nBeğendim uzattı beğendim numquam oldular camisi çobanın.\nMakinesi çakıl sıla ipsam qui layıkıyla koşuyorlar.\nSayfası mi ut masaya et sit suscipit doğru eius.\nİpsa masaya incidunt.\nEius şafak quia yazın orta telefonu totam.",
                            Status = 1
                        },
                        new
                        {
                            ID = 8,
                            CategoryName = "Games",
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 427, DateTimeKind.Local).AddTicks(9456),
                            Description = "Makinesi sevindi sevindi.\nConsequatur suscipit dolorem rem eius lambadaki ekşili.\nLayıkıyla ekşili lakin blanditiis sed ki dolores doloremque çorba molestiae.\nBilgisayarı ut molestiae gazete sed gülüyorum.\nBeğendim ut açılmadan labore.\nDolorem ut incidunt odio eos göze karşıdakine.\nConsequuntur gül beatae enim ki patlıcan magni otobüs.\nDeleniti sunt patlıcan.\nAut sarmal de nisi velit.\nFugit kapının çorba voluptatem odit.",
                            Status = 1
                        },
                        new
                        {
                            ID = 9,
                            CategoryName = "Computers",
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 427, DateTimeKind.Local).AddTicks(9605),
                            Description = "Qui ex mutlu ışık.\nÇakıl ve çıktılar eum ut okuma labore.\nAperiam ex quis ki voluptatem aspernatur un quasi bahar alias.\nConsequatur qui dolor quia ki sunt voluptatem ab batarya.\nQui ona makinesi ut açılmadan.\nAb ut koyun.\nOdit cesurca batarya quasi ipsum labore masaya.\nEt et domates sunt gidecekmiş tempora quae mutlu aliquam.\nMinima mıknatıslı et sinema consequatur gül uzattı masaya.\nOrta de bilgisayarı incidunt ullam consequatur adanaya değerli.",
                            Status = 1
                        },
                        new
                        {
                            ID = 10,
                            CategoryName = "Health",
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 427, DateTimeKind.Local).AddTicks(9790),
                            Description = "İpsum odit masaya odio şafak sevindi.\nOkuma numquam quaerat ama consectetur.\nEnim yazın koyun salladı dolorem tempora alias.\nOrta iure makinesi labore çorba.\nÇünkü sıfat sit dolorem eve dışarı patlıcan lakin sunt dolor.\nAut laudantium in eum sokaklarda teldeki domates beğendim quia dicta.\nİnventore düşünüyor çarpan illo inventore amet aliquid aut aut.\nAdanaya nihil sinema.\nQuia ducimus un accusantium sayfası dolores ekşili yapacakmış.\nIşık sequi eius inventore eve.",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AppUserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnitInStock")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 428, DateTimeKind.Local).AddTicks(21),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Gorgeous Metal Hat",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 555.19m
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 2,
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 428, DateTimeKind.Local).AddTicks(243),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Incredible Fresh Sausages",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 514.94m
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 3,
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 428, DateTimeKind.Local).AddTicks(300),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Refined Fresh Keyboard",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 463.66m
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 4,
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 428, DateTimeKind.Local).AddTicks(370),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Rustic Granite Ball",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 278.82m
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 5,
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 428, DateTimeKind.Local).AddTicks(408),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Generic Concrete Tuna",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 192.07m
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 6,
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 428, DateTimeKind.Local).AddTicks(452),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Ergonomic Rubber Chips",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 389.40m
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 7,
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 428, DateTimeKind.Local).AddTicks(490),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Practical Metal Hat",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 27.98m
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 8,
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 428, DateTimeKind.Local).AddTicks(527),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Small Soft Towels",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 762.77m
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 9,
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 428, DateTimeKind.Local).AddTicks(601),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Handmade Rubber Computer",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 254.17m
                        },
                        new
                        {
                            ID = 10,
                            CategoryID = 10,
                            CreatedDate = new DateTime(2024, 5, 21, 14, 43, 20, 428, DateTimeKind.Local).AddTicks(637),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Ergonomic Steel Gloves",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 702.62m
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.UserProfile", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserRole", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithMany("Orders")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.OrderDetail", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.UserProfile", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithOne("UserProfile")
                        .HasForeignKey("Project.ENTITIES.Models.UserProfile", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("UserProfile")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
