// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.DAL.ContextClasses;

#nullable disable

namespace Project.DAL.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 816, DateTimeKind.Local).AddTicks(8311),
                            Name = "Admin",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 816, DateTimeKind.Local).AddTicks(8359),
                            Name = "Member",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("ActivationCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Automotive",
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 816, DateTimeKind.Local).AddTicks(8401),
                            Description = "Dağılımı öyle aut consequatur sit magnam gül ipsam gitti camisi.\nVoluptatem doğru voluptatem balıkhaneye enim laboriosam alias minima aut.\nMinima ışık salladı voluptatem consequuntur kulu çakıl.\nÇünkü doğru masanın filmini değirmeni laboriosam qui ea gülüyorum aperiam.\nUt qui vitae çorba consequuntur perferendis.\nBatarya ut odit ut qui.\nHesap aliquid hesap çakıl veniam veniam.\nDüşünüyor esse voluptatum rem oldular vitae öyle eve.\nQui teldeki ut enim magnam layıkıyla ducimus çarpan dignissimos.\nNisi gidecekmiş laboriosam.",
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Kids",
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 816, DateTimeKind.Local).AddTicks(8960),
                            Description = "Salladı ona ut.\nÇakıl ki türemiş sokaklarda et filmini voluptatem.\nKoştum kalemi masanın.\nYazın mıknatıslı veritatis quia ut consequatur.\nAmet gül gördüm sit sevindi ötekinden eve.\nNisi ipsum mutlu değirmeni voluptatum.\nQuis çobanın veritatis.\nVoluptatem alias aut vitae perferendis ona exercitationem dolorem.\nTv türemiş sed aut mutlu ea.\nTv ışık kulu ea vitae sokaklarda eaque qui ex quam.",
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Baby",
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 816, DateTimeKind.Local).AddTicks(9166),
                            Description = "İpsa duyulmamış çobanın et bilgiyasayarı laudantium gazete.\nSalladı eve mıknatıslı totam voluptatem ut bundan eum.\nNumquam praesentium sit velit koşuyorlar architecto voluptatem bilgisayarı ratione.\nEve adanaya çobanın quasi.\nÖtekinden eum ipsam aperiam balıkhaneye.\nLaudantium çakıl kalemi camisi.\nTv velit çobanın.\nTüremiş lambadaki gitti eve.\nİncidunt nesciunt quia consequatur dolor tv karşıdakine ipsa eum ratione.\nUmut dolore perferendis camisi et beğendim sokaklarda quis odit dolore.",
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Garden",
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 816, DateTimeKind.Local).AddTicks(9362),
                            Description = "Mıknatıslı labore molestiae salladı cesurca.\nGazete odio veritatis çıktılar lambadaki teldeki nihil.\nSıla masaya beğendim.\nYaptı consequuntur batarya doloremque.\nAlias adipisci aut.\nConsequatur quis voluptatum gitti labore illo uzattı.\nMolestiae dicta quis iusto eos göze.\nSit corporis quia.\nBahar beatae dignissimos türemiş.\nOna aliquid çünkü vitae ötekinden kalemi nisi nisi.",
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Toys",
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 816, DateTimeKind.Local).AddTicks(9548),
                            Description = "Sarmal bundan sed ad incidunt dolores esse dolore et laboriosam.\nAma bahar sıradanlıktan sevindi filmini mutlu.\nNostrum sokaklarda filmini bilgisayarı ut accusantium oldular laudantium.\nRem dicta masanın odit sarmal.\nTelefonu göze odit ab nihil ut.\nVeniam quasi umut amet ki layıkıyla aperiam dolor cezbelendi.\nİure filmini autem masaya göze bahar.\nOtobüs göze magnam.\nCesurca telefonu iure.\nArchitecto et ut dolore.",
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            CategoryName = "Kids",
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 816, DateTimeKind.Local).AddTicks(9728),
                            Description = "Voluptate ona telefonu iure gidecekmiş consequuntur dignissimos labore.\nVoluptatem gülüyorum sinema.\nAdanaya göze aliquid ipsum gitti illo.\nEt magnam kutusu masanın uzattı otobüs voluptatem türemiş orta kalemi.\nBatarya veritatis un gülüyorum açılmadan de magnam consequatur değerli magnam.\nLakin architecto türemiş nihil ipsa corporis filmini.\nAliquid eius uzattı.\nİpsum ipsam kutusu kapının.\nAdanaya filmini de layıkıyla oldular veniam ut mi ki.\nNisi kalemi bahar quaerat consectetur çorba eius alias yaptı gülüyorum.",
                            Status = 1
                        },
                        new
                        {
                            ID = 7,
                            CategoryName = "Toys",
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 816, DateTimeKind.Local).AddTicks(9902),
                            Description = "Cezbelendi telefonu sıradanlıktan magni.\nEa voluptatem non ipsa dağılımı filmini masanın otobüs bilgisayarı ducimus.\nConsequatur aut sed.\nDoğru koşuyorlar nihil değirmeni orta sit.\nQui gitti exercitationem yazın.\nKoştum yazın camisi odio batarya qui lakin in minima oldular.\nMagnam gül architecto çıktılar nostrum değerli modi bahar eos.\nBundan açılmadan ki ratione olduğu sit göze anlamsız labore masaya.\nKutusu okuma ipsa velit beatae aliquam lambadaki.\nSıfat sevindi voluptatem commodi gördüm.",
                            Status = 1
                        },
                        new
                        {
                            ID = 8,
                            CategoryName = "Sports",
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 817, DateTimeKind.Local).AddTicks(71),
                            Description = "Velit koştum batarya.\nDuyulmamış kutusu consequatur laudantium reprehenderit değerli neque teldeki sunt.\nNon layıkıyla yapacakmış neque ışık enim.\nTempora non ab adresini quia düşünüyor değirmeni patlıcan corporis.\nEt masanın öyle dolorem doğru ut aut.\nLambadaki adanaya aut beğendim ona voluptatem.\nÇıktılar çünkü ducimus corporis mutlu enim.\nAut velit sed inventore ama non karşıdakine.\nAdresini iure autem kutusu sinema koyun için laboriosam alias.\nNihil vel dolores sed nemo değirmeni.",
                            Status = 1
                        },
                        new
                        {
                            ID = 9,
                            CategoryName = "Outdoors",
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 817, DateTimeKind.Local).AddTicks(275),
                            Description = "Odit illo molestiae ad sarmal ipsum quam mıknatıslı.\nÇobanın aliquid aut layıkıyla bilgisayarı öyle un fugit.\nNesciunt in şafak quaerat nostrum.\nBatarya voluptas minima.\nVoluptatem sit blanditiis nemo amet.\nSarmal quia enim.\nDe tv ea göze nesciunt.\nÇünkü ad otobüs değirmeni.\nEius sokaklarda sandalye yaptı mıknatıslı.\nIşık değerli ut ipsam adresini ad.",
                            Status = 1
                        },
                        new
                        {
                            ID = 10,
                            CategoryName = "Automotive",
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 817, DateTimeKind.Local).AddTicks(423),
                            Description = "Ratione non mıknatıslı odit.\nMıknatıslı adanaya dışarı ekşili sandalye layıkıyla.\nGülüyorum tempora aut ışık çakıl consequatur.\nMagni makinesi aut değirmeni ipsa dergi un nisi doloremque.\nSandalye magnam gül architecto.\nEve makinesi incidunt doğru modi öyle.\nİçin cesurca ullam voluptatum masanın bilgisayarı quia numquam teldeki lakin.\nExercitationem gül iusto değirmeni sunt duyulmamış ex.\nAliquid sed çakıl.\nMakinesi odit masanın değirmeni aut odio çakıl ut.",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AppUserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnitInStock")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 817, DateTimeKind.Local).AddTicks(635),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Small Frozen Chips",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 35.20m
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 2,
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 817, DateTimeKind.Local).AddTicks(850),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Incredible Steel Bike",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 324.38m
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 3,
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 817, DateTimeKind.Local).AddTicks(930),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Small Concrete Bacon",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 324.36m
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 4,
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 817, DateTimeKind.Local).AddTicks(975),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Generic Soft Sausages",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 616.86m
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 5,
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 817, DateTimeKind.Local).AddTicks(1016),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Rustic Metal Computer",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 327.34m
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 6,
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 817, DateTimeKind.Local).AddTicks(1058),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Refined Rubber Salad",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 72.84m
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 7,
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 817, DateTimeKind.Local).AddTicks(1099),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Generic Soft Gloves",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 630.71m
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 8,
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 817, DateTimeKind.Local).AddTicks(1175),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Gorgeous Soft Keyboard",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 721.47m
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 9,
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 817, DateTimeKind.Local).AddTicks(1213),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Small Concrete Cheese",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 513.75m
                        },
                        new
                        {
                            ID = 10,
                            CategoryID = 10,
                            CreatedDate = new DateTime(2024, 5, 27, 22, 57, 5, 817, DateTimeKind.Local).AddTicks(1254),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Handmade Fresh Table",
                            Status = 1,
                            UnitInStock = 100,
                            UnitPrice = 471.05m
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.UserProfile", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Yaradılış Tarihi");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserRole", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithMany("Orders")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.OrderDetail", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.UserProfile", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithOne("UserProfile")
                        .HasForeignKey("Project.ENTITIES.Models.UserProfile", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("UserProfile")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
